### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by danielberkompas** [danielberkompas/telephonist#1]
The README and generated docs should give the user enough information to fully understand how Telephonist works.

**Comment by cloudbring** [comment]
@danielberkompas I've looked at this and your other work with [ex_twiml](https://github.com/danielberkompas/ex_twiml). I'm wondering, **can I use this state machine with the `SMS` verb** or are there call specific things in here?

**Comment by danielberkompas** [comment]
@cloudbring You could use this with the `SMS` verb, yes. Do you have a specific use case in mind?

**Comment by cloudbring** [comment]
I'm trying to tie SMS messages to an in-browser chat session with JS.
Basically allow the users of the app I'm building to chat with people over
SMS. I was thinking that Elixir and Phoenix's support for channels would be
a good choice for my usecase. Do you agree and would telephonist be up to
the job?

**Comment by danielberkompas** [comment]
I think Elixir, Phoenix and Twilio would be a good fit for what you're building, but I don't think you need Telephonist for that. Telephonist is primarily intended to help manage inbound phone calls, for example, for a help desk. It's not really needed to handle inbound/outbound SMS.

It sounds like your app would have two main transactions:

#### 1. User sends message from JS chat
- Message is sent over websockets to Phoenix channel
- App decides what phone number needs to be sent an SMS
- Contact Twilio REST API to send an SMS message to that phone number

#### 2. User sends SMS from phone
- Message is sent to a Twilio phone number
- Twilio posts information about the SMS message, including the number it was sent to, to an endpoint on your Phoenix app
- Your app interprets what JS chat this message belongs to, and broadcasts the message on the appropriate Phoenix channel.
- Message comes through websockets to JS client
- Display to user

Telephonist doesn't fit into this picture. However, another library I wrote, [ExTwilio](https://github.com/danielberkompas/ex_twilio) might be useful for the Twilio API calls you'd need to make.

**Comment by cloudbring** [comment]
Thanks for the advice! I'm gonna take that to heart and try and build it
out over the next couple of weekends.

I saw ExTwillio. Looks good, can't wait to jump in and start playing
around.

So, I wrote up a little Gist kinda outlining what's in the Phoenix
Ecosystem as of June 2015 (in the context of writing this app) and I list
your Twilio packages (among other things).  Take a look and let me know
what you think and if there's anything that's missing.

##### [_j.mp/phoenix_ecosystem_June2015_](http://j.mp/phoenix_ecosystem_June2015)

Best,

Emmanuel
