### ISSUE TITLE
Access to current state from within transition?

### ISSUE THREAD

**Issue by brentonannan** [danielberkompas/telephonist#5]
Hi Daniel,

I'm having some trouble with keeping state between many calls to `process`. e.g: I have a menu that prompts for an eta, then confirms that eta, and I would like to then keep that eta in state:

```
  state :prompt, _twilio, _job do
    gather method: "GET" do
      say dgettext("call_flows.job.update_eta", "Enter the ETA time in minutes and then press #, or press # to go back"), voice: "alice", language: Gettext.get_locale(TelephoneProvisioner.Gettext)
    end
    redirect method: "GET"
  end   

  state :confirmation, _twilio, %{eta: %{unconfirmed: minutes}} do
    gather numDigits: 1, method: "GET" do
      say dgettext("call_flows.job.update_eta", "The time you entered is %{eta} minutes", %{eta: minutes}), voice: "alice", language: Gettext.get_locale(TelephoneProvisioner.Gettext)
      say menu_option("1", dgettext("call_flows.job.update_eta", "if this is correct")), voice: "alice", language: Gettext.get_locale(TelephoneProvisioner.Gettext)
      say menu_option("2", dgettext("call_flows.job.update_eta", "to update the ETA")), voice: "alice", language: Gettext.get_locale(TelephoneProvisioner.Gettext)
    end   
  end 

  state :confirmed, _twilio, job do
    say dgettext("call_flows.job.update_eta", "ETA confirmed at %{eta} minutes", %{eta: minutes}), voice: "alice", language: Gettext.get_locale(TelephoneProvisioner.Gettext)
    redirect method: "GET"
  end   

  def transition(:prompt, %{Digits: minutes} = twilio, job) do
    job = Map.put(job, :eta, %{unconfirmed: minutes})
    state :confirmation, twilio, job
  end 

  def transition(:confirmation, %{Digits: "1"} = twilio, job) do
    state :confirmed, twilio, job
  end   

  def transition(:confirmation, %{Digits: "2"} = twilio, job) do
    state :prompt, twilio, job
  end   
```

The problem is that I don't have access to the `job.eta.unconfirmed` from the `:confirmation` state when I get to the `def transition(:confirmation, %{Digits: "1"} = twilio, job)` - `job` is newly injected from the `process` call on my HTTP endpoint.

Is there a way to use the existing state in transitions?

As a side note, you can see that I'm having to repeat `voice: "alice", language: Gettext.get_locale(...)` for all of my say calls - is there a way around this?

Cheers,
Brenton.

**Comment by danielberkompas** [comment]
This sounds like it could be a bug. I'll see if I can reproduce it in a test case and then fix it. The existing state _should_ be passed through for the whole duration of a call.

**Comment by brentonannan** [comment]
`state.name` is passed to `transition` [here](https://github.com/danielberkompas/telephonist/blob/master/lib/telephonist/call_processor.ex#L98) for pattern matching against, but the `state.options` isn't.

It'd be a breaking change, but you could pass the whole state, and patten match from within that instead, that way a user could combine current state data, `twilio`, and `options` on to create the data for the next state.

**Comment by danielberkompas** [comment]
@brentonannan I wrote this test case to try to reproduce, and couldn't: https://github.com/danielberkompas/telephonist/commit/f26bbd3fa554114a5d3356160159d626c608b8ff

Are you sure you are on the latest version of Telephonist?

Regarding the `say` problem, it looks like you're stuck with that for now. `ExTwiml` needs to be updated to support passing a variable for verb options, like so:

``` elixir
options = [voice: "alice"]
say "Hello", options
say "World", options
```

**Comment by brentonannan** [comment]
It's actually in the second transition - from `:confirmation` to `:confirmed` that the data is lost - because it's available as part of the `:confirmation` state, but that's not available in the `transition`.

**Comment by brentonannan** [comment]
Also, what would be nice for ExTwiml is if known tags could have known attributes set in config (although that wouldn't help with dynamic ones like my `language: Gettext.getlocale(...)`. I've been trying, unsuccessfully so far, to write macros to wrap say, not sure if I'm barking up the wrong tree there.

**Comment by danielberkompas** [comment]
@brentonannan I just made a new release of ExTwiml which allows you to set default attributes for verbs: https://github.com/danielberkompas/ex_twiml/releases/tag/v2.1.0
